<?php

require drupal_get_path('module', 'tripal_elasticsearch') . '/api/bootstrap.php';


set_time_limit(0);


/**
 * Implementation of hook_menu().
 */
function tripal_elasticsearch_menu()
{
    //$pre = 'admin/config/search/elastic_search';
    $pre = 'admin/tripal/extension/tripal_elasticsearch';
    $items[$pre] = array(
        'title' => 'Tripal Elasticsearch',
        'description' => 'Configure elastic indexing and build search interface',
        'page callback' => 'drupal_goto',
        'page arguments' => array($pre . '/admin_pages'),
        'access callback' => 'user_access',
        'access arguments' => array('administer users'),
    );
    $items[$pre . '/admin_pages'] = array(
        'title' => 'Tripal Elasticsearch Administration',
        'description' => 'Tripal Elasticsearch Administration Pages',
        'page callback' => 'tripal_elasticsearch_admin_page',
        'access callback' => 'user_access',
        'access arguments' => array('administer users'),
        'file' => 'tripal_elasticsearch.admin.inc',
    );

    $items[$pre . '/connect_to_elasticsearch_cluster'] = array(
        'title' => t('Connect to elasticsearch cluster'),
        'page callback' => 'connect_to_elasticsearch_cluster_page',
        'access callback' => 'user_access',
        'access arguments' => array('administer users'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'tripal_elasticsearch.admin.inc',
        'weight' => 1,
    );

    //========= indices management ========
    //
    //=====================================
    $items[$pre . '/indices_management'] = array(
        'title' => t('Indexing Website'),
        'page callback' => 'indexing_website_page',
        'access callback' => 'user_access',
        'access arguments' => array('administer users'),
        'type' => MENU_NORMAL_ITEM,
        'weight' => 2,
        'file' => 'tripal_elasticsearch.admin.inc',
    );
    $items[$pre . '/indices_management/indexing_website'] = array(
        'title' => t('Indexing Website'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
    );
    $items[$pre . '/indices_management/indexing_database_table'] = array(
        'title' => t('Indexing Database Table'),
        'page callback' => 'indexing_database_table_page',
        'access callback' => 'user_access',
        'access arguments' => array('administer users'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
        'file' => 'tripal_elasticsearch.admin.inc',
    );
    $items[$pre . '/indices_management/delete_indices'] = array(
        'title' => t('Delete Indices'),
        'page callback' => 'delete_indices_page',
        'access callback' => 'user_access',
        'access arguments' => array('administer users'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 3,
        'file' => 'tripal_elasticsearch.admin.inc',
    );


    // ============= elastic search ===========
    //
    // ========================================
    $items[$pre . '/search'] = array(
        'title' => t('Build search forms'),
        'page callback' => 'build_search_forms_page',
        'access callback' => 'user_access',
        'access arguments' => array('administer users'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'tripal_elasticsearch.admin.inc',
    );
    $items[$pre . '/search/build_search_forms'] = array(
        'title' => t('Build search forms'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 1,
    );
    $items[$pre . '/search/delete_search_forms'] = array(
        'title' => t('Delete search forms'),
        'page callback' => 'delete_search_forms_page',
        'access callback' => 'user_access',
        'access arguments' => array('administer users'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 2,
        'file' => 'tripal_elasticsearch.admin.inc',
    );
    /*
    $items[$pre . '/search/link_results_to_pages'] = array(
        'title' => t('Link results to pages'),
        'page callback' => 'link_results_to_pages_page',
        'access callback' => 'user_access',
        'access arguments' => array('administer users'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 3,
        'file' => 'tripal_elasticsearch.admin.inc',
    );
    $items[$pre . '/search/alter_search_forms'] = array(
        'title' => t('Alter search forms'),
        'page callback' => 'alter_search_forms_page',
        'access callback' => 'user_access',
        'access arguments' => array('administer users'),
        'type' => MENU_LOCAL_TASK,
        'weight' => 4,
        'file' => 'tripal_elasticsearch.admin.inc',
    );
    */

    $items['website-search/%'] = [
        'title' => t('Website Search'),
        'page callback' => 'website_search_results_page',
        'page arguments' => array(1),
        'access callback' => true,
    ];

    return $items;
}


function website_search_results_page($node_type)
{

    return '';
}

/**
 * Implements hook_block_info().
 */
function tripal_elasticsearch_block_info()
{
    $blocks = array();
    // Block for main search box.
    $blocks['_sitewide_search_box'] = array(
        'info' => t('tripal_elasticsearch sitewide search box'),
        'status' => TRUE,
        'region' => 'help',
        'cache' => DRUPAL_NO_CACHE,
        'weight' => -99,
    );
    // Block for main search results
    $blocks['_sitewide_search_results'] = array(
        'info' => t('tripal_elasticsearch sitewide search results'),
        'status' => TRUE,
        'region' => 'content',
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => "website-search\nwebsite-search/*",
        'cache' => DRUPAL_NO_CACHE,
    );

    //=================TODO======================
    //
    //===========================================
    /*
    // block for website search categories
    $blocks['_sitewide_search_categories'] = [
        'info' => t('tripal_elasticsearch sitewide search categories'),
        'status' => true,
        'region' => 'content',
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => "website-search\nwebsite-search/*",
        'cache' => DRUPAL_NO_CACHE,
    ];
    */
    //=========== ENDofTODO =====================

    /*
     * build blocks for each table in the tripal_elasticsearch_search_forms database table
     */
    $result = db_query('SELECT DISTINCT(table_name) FROM tripal_elasticsearch_search_forms');
    foreach ($result as $record) {
        // For some reason, block name cannot be longer than 32 chars
        // prefix table name with "sf_" and use it for search form block names
        // sf stands for search form
        $block_name_form = '_sf_' . $record->table_name;
        $blocks[$block_name_form] = array(
            'info' => t(
                'tripal_elasticsearch search form: ' . $record->table_name
            ),
            'status' => TRUE,
            'region' => 'content',
            'visibility' => BLOCK_VISIBILITY_LISTED,
            'pages' => "elastic_search\nelastic_search/*",
            'cache' => DRUPAL_NO_CACHE,
        );
        // prefix table name with "sr_" and use it for search result block names
        // sr stands for search result
        $block_name_hits = '_sr_' . $record->table_name;
        $blocks[$block_name_hits] = array(
            'info' => t(
                'tripal_elasticsearch search results: ' . $record->table_name
            ),
            'status' => TRUE,
            'region' => 'content',
            'visibility' => BLOCK_VISIBILITY_LISTED,
            'pages' => "elastic_search\nelastic_search/*",
            'cache' => DRUPAL_NO_CACHE,
        );
    }

    return $blocks;
}


/**
 * Implements hook_block_view().
 */
function tripal_elasticsearch_block_view($delta = '')
{

    $block = array();

    // identify search form and search result blocks
    $block_type = '';
    $table_name = '';
    if (preg_match('/^(_sf_)/', $delta)) {
        $block_type = 'search_form_block';
        $table_name = preg_replace('/^(_sf_)/', '', $delta);
    }
    if (preg_match('/^(_sr_)/', $delta)) {
        $block_type = 'search_result_block';
        $table_name = preg_replace('/^(_sf_)/', '', $delta);
    }
    if ($delta == "_sitewide_search_box") {
        $block_type = '_sitewide_search_box';
    }
    if ($delta == "_sitewide_search_results") {
        $block_type = '_sitewide_search_results';
    }
    if ($delta == "_sitewide_search_categories") {
        $block_type = '_sitewide_search_categories';
    }

    switch ($block_type) {
        case 'search_form_block':
            $block['subject'] = $delta;
            $block['content'] = drupal_get_form(
                'view_search_forms_form',
                $table_name
            );
            break;
        case 'search_result_block':
            $block['subject'] = $delta;
            //$block['content'] = !empty($search_hits_table) ? $search_hits_table : '';
            if (isset($_GET['_table_name']) && !empty($_GET['_table_name'])) {
                $block['content'] = theme('database_table_search_results', ['table_name' => $_GET['_table_name']]);
            } else {
                $block['content'] = 'No records were found';
            }
            break;
        case '_sitewide_search_box':
            $block['subject'] = '';
            $block['content'] = drupal_get_form('sitewide_search_box_form');
            break;
        case '_sitewide_search_results':
            $block['subject'] = '';

            if (isset($_GET['sitewide_search_box']) && !empty($_GET['sitewide_search_box'])) {
                $search_content = $_GET['sitewide_search_box'];

                /*
                // run elastic search
                $connection = (new ElasticConnection(["127.0.0.1:9201"]))->make();
                $elastic_search = new ElasticSearch($connection);
                $params = $elastic_search->build_website_search_params($index = 'website', $type = 'website', $search_content = $search_content, $from = 0, $size = 1000);
                $search_res = $elastic_search->website_search($params);
                $elastic_search->search_count($params);

                if (!empty($search_res)) {
                    $block['content'] = theme('website_search_results', ['website_search_results' => $search_res]);
                } else {
                    $block['content'] = 'No records were found.';
                }
                */
                $block['content'] = theme('website_search_results', ['search_content' => $search_content]);
            } else {
                $block['content'] = 'No records were found.';
            }
            break;

        //=================TODO======================
        //
        //===========================================
        /*
        case '_sitewide_search_categories':
            $block['subject'] = t('Search result categories');

            if (isset($_GET['sitewide_search_box']) && !empty($_GET['sitewide_search_box'])) {
                $search_content = $_GET['sitewide_search_box'];
                // run elastic search
                $connection = (new ElasticConnection(["127.0.0.1:9201"]))->make();
                $elastic_search = new ElasticSearch($connection);
                $params = $elastic_search->build_website_search_params($index='website', $type='website', $search_content=$search_content, $from=0, $size=1000);
                $search_res = $elastic_search->website_search($params);



                $block['content'] = theme('website_search_categories', ['website_search_results' => $search_res, 'search_content' => $search_content]);
            } else {
                $block['content'] = 'categories';
            }
        */


    }


    /*
    drupal_add_js(
        drupal_get_path('module', 'tripal_elasticsearch') . '/js/hit_description.js'
    );
    */

    return $block;
}


/**
 * implement hook_cron_queue_info()
 */
function tripal_elasticsearch_cron_queue_info()
{
    // Define N=10 queues
    $queue_N = 10;
    for ($n = 0; $n < $queue_N; $n++) {
        $queues['elastic_queue_' . $n] = array(
            'worker callback' => 'elastic_indexing_queue_item',
            //'time' => 60 * 60 * 2,  ## the amount of time drupal spends on calling the worker function.
            'time' => 115,
        );
    }

    return $queues;
}


/**
 * queue worker function
 */
function elastic_indexing_queue_item($item)
{
    $client = (new ElasticConnection(["localhost:9201"]))->make();
    $cron_queue_worker = new CronQueueWorker($client, $item);
    $cron_queue_worker->indexing();
}


/**
 * implements hook_node_update().
 * Any node updates will also update the corresponding elasticsearch docs.
 */
function tripal_elasticsearch_node_update($node)
{
    $queue_N = 10;
    // randomly assign the updated node to a queue
    $n = rand(0, $queue_N - 1);
    $queue = DrupalQueue::get('elastic_queue_' . $n);
    $nid = $node->nid;
    $sql = "SELECT title,nid,type FROM node WHERE nid=$nid ;";

    $connection = (new ElasticConnection(['localhost:9201']))->make();
    $elastic_index = new ElasticIndex($connection);
    $field_mapping_types = $elastic_index->GetFieldMappingTypes('website');

    $item = new stdClass();
    $item->index = 'website';
    $item->table = 'node';
    $item->is_website = True;
    $item->sql = $sql;
    $item->website_base_url = variable_get('website_base_url', 'http://localhost:80');
    $item->field_mapping_types = $field_mapping_types;
    $queue->createItem($item);
}

/**
 * implements hook_node_insert().
 * Any new nodes will be added to the  elasticsearch cron queue.
 */
function tripal_elasticsearch_node_insert($node)
{


    $queue_N = 10;
    // randomly assign the inserted node to a queue
    $n = rand(0, $queue_N - 1);
    $queue = DrupalQueue::get('elastic_queue_' . $n);
    $nid = $node->nid;
    $sql = "SELECT title,nid,type FROM node WHERE nid=$nid ;";

    $connection = (new ElasticConnection(['localhost:9201']))->make();
    $elastic_index = new ElasticIndex($connection);
    $field_mapping_types = $elastic_index->GetFieldMappingTypes('website');

    $item = new stdClass();
    $item->index = 'website';
    $item->table = 'node';
    $item->is_website = True;
    $item->sql = $sql;
    $item->website_base_url = variable_get('website_base_url', 'http://localhost:80');
    $item->field_mapping_types = $field_mapping_types;
    $queue->createItem($item);
}


/**
 * Implements hook_node_delete().
 * the indexed doc for the deleted node will be also deleted in elasticsearch
 */
function tripal_elasticsearch_node_delete($node)
{
    /*
    $nid = $node->nid;
    $params = array();
    $params = [
        'index' => 'index_website',
        'type' => 'index_website',
        'id' => $nid,
        'body' => ['fake_field' => 'fake document'],
    ];
    // create a fake document and index it in case that the node
    // that is being deleted doesn't exit in elasticsearch
    $client = Elasticsearch\ClientBuilder::create()->setHosts(
        variable_get('elasticsearch_hosts', array('localhost:9200'))
    )->build();
    $client->index($params);


    $params = array();
    $params = [
        'index' => 'index_website',
        'type' => 'index_website',
        'id' => $nid,
    ];
    $client->delete($params);
    */
}


/*
 * implement hook_theme.
 */
function tripal_elasticsearch_theme($existing, $type, $theme, $path)
{
    $theme_hooks['database_table_search_results'] = [
        'variables' => [
            'table_name' => null,
        ],
        'file' => 'tripal_elasticsearch.theme.inc',
    ];
    $theme_hooks['website_search_results'] = [
        'variables' => [
            'search_content' => null,
        ],
        'file' => 'tripal_elasticsearch.theme.inc',
    ];
    $theme_hooks['website_search_categories'] = [
        'variables' => [
            'website_search_results' => null,
            'search_content' => null,
        ],
        'file' => 'tripal_elasticsearch.theme.inc',
    ];

    return $theme_hooks;
}

